---
- name: "Load Balancer | {{ role_name }}"
  ec2_elb_lb:
    state: present
    region: "{{ region }}"
    name: "{{ project }}-{{ role_name }}"
    security_group_ids: "{% for security_group in load_balancer[role_name].security_groups %}{{ security_group_id[security_group] }}{% if not loop.last %},{% endif %}{% endfor %}"
    listeners: "{{ load_balancer[role_name].listeners }}"
    scheme: "{{ load_balancer[role_name].scheme }}"
    subnets: "{{ vpc.subnets | selectattr('resource_tags.Role', 'equalto', role_name) | map(attribute='id') | list }}"
    cross_az_load_balancing: yes
  register: balancer

- name: "Capture Load Balancer Name | {{ role_name }}"
  set_fact:
    load_balancer_name: "{{ load_balancer_name.update({role_name: balancer.elb.name}) }}{{ load_balancer_name }}"

- name: "Route53 Record | {{ role_name }}.{{ project }}-{{ environment_tier }}.teluswebteam.com"
  route53:
    command: create
    overwrite: yes
    zone: teluswebteam.com
    record: "{{ role_name }}.{{ project }}-{{ environment_tier }}.teluswebteam.com"
    type: CNAME
    value: "{{ balancer.elb.dns_name }}"
    ttl: 300
  when: dns_points_to_load_balancer
  tags:
    - dns
