---
- name: "Load Balancer | {{ role }}"
  ec2_elb_lb:
    state: present
    region: "{{ region }}"
    name: "{{ project }}-{{ role }}"
    security_group_ids: "{% for security_group in load_balancer[role].security_groups %}{{ security_group_id[security_group] }}{% if not loop.last %},{% endif %}{% endfor %}"
    listeners: "{{ load_balancer[role].listeners }}"
    scheme: "{{ load_balancer[role].scheme }}"
    subnets: "{{ vpc.subnets | selectattr('resource_tags.Role', 'equalto', role) | map(attribute='id') | list }}"
  register: balancer

- name: "Capture Load Balancer Name | {{ role }}"
  set_fact:
    load_balancer_name: "{{ load_balancer_name.update({role: balancer.elb.name}) }}{{ load_balancer_name }}"

- name: "Route53 Record | {{ role }}.{{ project }}-{{ environment_tier }}.teluswebteam.com"
  route53:
    command: create
    overwrite: yes
    zone: teluswebteam.com
    record: "{{ role }}.{{ project }}-{{ environment_tier }}.teluswebteam.com"
    type: CNAME
    value: "{{ balancer.elb.dns_name }}"
    ttl: 300
  when: dns_points_to_load_balancer
  tags:
  - dns