---
- name: Create Database Subnet Group
  rds_subnet_group:
    state: present
    name: "{{ project }}-{{ role }}"
    description: "Database for {{ project }}"
    region: "{{ region }}"
    subnets: "{{ vpc.subnets | selectattr('resource_tags.Role', 'equalto', role) | map(attribute='id') | list }}"

- name: Create Database Servers
  rds:

    command: create

    region: "{{ region }}"
    multi_zone: yes

    instance_name: "{{ project }}-{{ role }}-{{ environment_tier }}"
    instance_type: "{{ database_rds_instance_type | mandatory }}"

    vpc_security_groups: "{{ security_group_id[role] }}"
    subnet: "{{ project }}-{{ role }}"

    db_engine: "{{ database_engine | mandatory }}"
    upgrade: yes

    port: "{% if database_engine == 'postgres' %}5432{%elif database_engine == 'MySQL' %}3306{% endif %}"
    db_name: "{{ database_name | default(project) }}"
    username: "{{ database_username | default(project) }}"
    password: "{{ database_password | mandatory }}"

    backup_retention: 30
    size: 100
    wait: yes
