---
- set_fact:
    instances: "{{ dict() }}"

- name: Identify Base Image for Region
  ec2_ami_search:
    arch: amd64
    distro: ubuntu
    region: "{{ region }}"
    release: trusty
    store: ebs-ssd
    stream: server
    virt: hvm
  register: base_image

- { include: create/instance.yml, system_role: management,  when: "'management' in required_systems" }
- { include: create/instance.yml, system_role: inbound,     when: "'inbound' in required_systems" }
- { include: create/instance.yml, system_role: application, when: "'application' in required_systems" }
- { include: create/instance.yml, system_role: cache,       when: "'cache' in required_systems" }
- { include: create/instance.yml, system_role: database,    when: "'database' in required_systems and not using_rds" }
- { include: create/instance.yml, system_role: outbound,    when: "'outbound' in required_systems" }
- { include: create/instance.yml, system_role: logs,        when: "'logs' in required_systems" }
- { include: create/instance.yml, system_role: metrics,     when: "'metrics' in required_systems" }
- { include: create/instance.yml, system_role: aggregator,  when: "'aggregator' in required_systems" }
- { include: create/instance.yml, system_role: build,       when: "'build' in required_systems" }
- { include: create/instance.yml, system_role: preview,     when: "'preview' in required_systems" }

- { include: create/rds-database.yml, system_role: database, when: "'database' in required_systems and using_rds" }
