---
- set_fact:
    instances: "{{ dict() }}"

- name: Identify Base Image for Region
  ec2_ami_search:
    region: "{{ region }}"
    distro: ubuntu
    release: trusty
    store: "{% if environment_tier in ['staging', 'production'] %}ebs{% else %}instance-store{% endif %}"
  register: base_image

- { include: create/instance.yml, role: management,  when: "'management' in required_systems" }
- { include: create/instance.yml, role: inbound,     when: "'inbound' in required_systems" }
- { include: create/instance.yml, role: application, when: "'application' in required_systems" }
- { include: create/instance.yml, role: cache,       when: "'cache' in required_systems" }
- { include: create/instance.yml, role: database,    when: "'database' in required_systems and using_rds == 'no'" }
- { include: create/instance.yml, role: outbound,    when: "'outbound' in required_systems" }
- { include: create/instance.yml, role: aggregator,  when: "'aggregator' in required_systems" }
- { include: create/instance.yml, role: build,       when: "'build' in required_systems" }

- { include: create/rds-database.yml, role: database, when: "'database' in required_systems and using_rds == 'yes'" }
