---
- include_vars: "environment_tier/{{ environment_tier | mandatory }}.yml"
- include_vars: infrastructure/subnets.yml
- include_vars: infrastructure/security-groups.yml
- include_vars: infrastructure/load-balancers.yml
- include_vars: infrastructure/instances.yml
- include_vars: "region/{{ region | mandatory }}.yml"

- include: create/vpc.yml
- include: security-groups.yml
- include: load-balancers.yml
- include: instances.yml
- { include: autoscaling.yml, when: "autoscale is defined" }
