---
- set_fact:
    security_group_id: "{{ dict() }}"

- { include: create/security-group.yml, role: management,     when: "'management' in required_systems" }
- { include: create/security-group.yml, role: managed }
- { include: create/security-group.yml, role: inbound,        when: "'inbound' in required_systems" }
- { include: create/security-group.yml, role: application,    when: "'application' in required_systems" }
- { include: create/security-group.yml, role: cache,          when: "'cache' in required_systems" }
- { include: create/security-group.yml, role: outbound,       when: "'outbound' in required_systems" }
- { include: create/security-group.yml, role: aggregator,     when: "'aggregator' in required_systems" }
- { include: create/security-group.yml, role: log-storage,    when: "'log-storage' in required_systems" }
