---
- set_fact:
    security_group_id: "{{ dict() }}"

- { include: create/security-group.yml, role: management }
- { include: create/security-group.yml, role: managed }
- { include: create/security-group.yml, role: inbound }
- { include: create/security-group.yml, role: application }
- { include: create/security-group.yml, role: cache }
- { include: create/security-group.yml, role: database,       when: "'database' in required_systems" }
- { include: create/security-group.yml, role: outbound,       when: "'outbound' in required_systems" }
- { include: create/security-group.yml, role: aggregator,     when: "'aggregator' in required_systems" }
- { include: create/security-group.yml, role: log-storage,    when: "'log-storage' in required_systems" }
- { include: create/security-group.yml, role: build,          when: "'build' in required_systems" }
- { include: create/security-group.yml, role: preview,        when: "'preview' in required_systems" }

- name: "No Management, Exposing Managed Systems"
  set_fact:
    security_group: "{{ security_group.update(no_management) }}{{ security_group }}"
  when: "'management' not in required_systems"

- { include: create/security-group.yml, role: managed, when: "'management' not in required_systems" }

- name: "No Inbound Proxies, Exposing Application Servers"
  set_fact:
    security_group: "{{ security_group.update(no_inbound) }}{{ security_group }}"
  when: "'inbound' not in required_systems"

- { include: create/security-group.yml, role: application, when: "'inbound' not in required_systems" }
