---
load_balancer:
  application:
    scheme: internet-facing
    security_groups: ['inbound', 'application']
    listeners:
    - protocol: http
      load_balancer_port: 80
      instance_port: 80
    - protocol: "{{ 'https' if elb_ssl_offload else 'tcp' }}"
      load_balancer_port: 443
      instance_port: "{{ 80 if elb_ssl_offload else 443 }}"
      instance_protocol: "{{ 'http' if elb_ssl_offload else 'tcp' }}"
      ssl_certificate_id: "{{ ( 'arn:aws:iam::461957644563:server-certificate/self-signed' + elb_ssl_certificate_name ) if elb_ssl_offload else omit }}"
  database:
    scheme: internal
    security_groups: ['application', 'database']
    listeners:
    - protocol: tcp
      load_balancer_port: 3306
      instance_port: 3306
    - protocol: tcp
      load_balancer_port: 5432
      instance_port: 5432
    - protocol: tcp
      load_balancer_port: 27017
      instance_port: 27017
  outbound:
    scheme: internal
    security_groups: ['application', 'outbound']
    listeners:
    - protocol: tcp
      load_balancer_port: 80
      instance_port: 80
    - protocol: tcp
      load_balancer_port: 443
      instance_port: 443
    - protocol: tcp
      load_balancer_port: 8080
      instance_port: 8080
    - protocol: tcp
      load_balancer_port: 8443
      instance_port: 8443
